### PR TITLE
Add incident handling procedures to Code of Conduct

### PR DESCRIPTION
**Pull request by jossiwolf**
This PR simply adds the `.md` files and links for incident handling procedures for both attendees and organizers.
I guess there should be some extra page for that, I can do that if needed.

### CODE REVIEW

**Comment by emedvedev** [comment]
I think an extra page would be great! Maybe even two, because it would be a good idea to keep the essential information for attendees short. We can link to both from the main CoC page.

**Comment by jossiwolf** [comment]
@emedvedev I added an extra page. Have a look around :)

I'll resolve the merge conflicts later.

There are still some formatting issues - @mfahlandt could you take a look? I'm not really well-versed in CSS.

**Comment by emedvedev** [comment]
Made some changes to the new pages. 

I'm also making the assumption that we're going to have a dedicated CoC response team — can be our existing happiness team or several people specifically tasked with incident response for the duration of the event (@Aadjou proposed the latter, and I also think it's a good idea).

As for the merge conflicts, here's an idea of how we could insert the links to the handling docs:

Attendees:

```Speak up. If you or someone else are being harassed, do not hesitate to contact the event staff (organizers or volunteers), who can be identified by special badges or attire. While we do our best to notice any case of harassment, we rely on your help and would greatly appreciate it. If you feel uncomfortable to report a violation in person, please do so at conduct@dachfest.com. You may want to take a look at the [violation reporting guidelines for attendees]() before submitting a report: it is not mandatory, but might help us handle the situation better and faster.```

Organizers:

```The conference organizers will maintain the anonymity of the offended party, unless specifically discussed and agreed not to, as well as the anonymity of the alleged offender during an ongoing investigation. For transparency, the incident handling procedures for staff members are publicly available and can be found at the [corresponding page]().```

Feel free to modify as you see fit! I'm also thinking it could be enough to acknowledge the Berlin CoC once on the main CoC page (without carrying it to subpages).

**Comment by jossiwolf** [comment]
@emedvedev Sorry for the long response time, those are awesome changes! I incorporated them. Please take a look!

@mfahlandt The styling seems off, could you please take a look? Or anybody that knows how to fight CSS? :p

**Pull request merged**
